### PR TITLE
Invert dark favicons (#114)

### LINKED ISSUE #114: Better display for dark favicons in the dark theme
Dakr favicons (e.g. GitHub's one) are poorly visible when using dark theme. They should be inversed or highlighted in some other way.

Here is an example how they did it in Opera:
https://blogs.opera.com/desktop/2017/06/opera-47-beta/

### LINKED ISSUE #144: Integrate with the current theme
From 58 onwards, you can get the current theme properties: 

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/theme/getCurrent

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/theme/onUpdated

Why is this useful ?
Integrating with dynamic themes like [VivaldiFox](https://addons.mozilla.org/en-US/firefox/addon/vivaldifox/) or [Container Theme](https://addons.mozilla.org/en-US/firefox/addon/containers-theme/)

A lot of people have expressed their wish to see VivaldiFox work with their favourite sidebar tabs add-on.

### PR DESCRIPTION
**Pull request by mmktomato**
I've fixed #114 . I added an external library in order to detect dark favicon.
https://github.com/fast-average-color/fast-average-color

### CODE REVIEW

**Comment by mmktomato** [comment]
Oops, I didn't notice that CI is failed. I'll fix it later.

**Comment by Croydon** [comment]
Thank you so much for working on this!

I have merged this via e901efcb97187a228d30dac249c659b4b7ed3359 in the 0.13.0 branch and gave it a bit of fine tuning via dda4587c7af0a7ad777ebd3739eefc2ed6e45938 and 7f8d4d3ff52e927aac68ec81283d88be91de958a

It is live now in the [dev version](https://addons.mozilla.org/en-US/firefox/addon/vtr-developer-version/). I want to use it for a few days in "real world browsing" before I merge it into master, but looks pretty good 👍

**Comment by Croydon** [comment]
> Could you close this PR after you merge it into master?

Yes, I will do this.

My first impression is, that it will need some further work. Likely some calculation of the contrast between the average icon color and the tab color to determinate if it should get inverted. Right now the Netflix logo is getting inverted even though it is (in my opinion) very noticeable and doesn't need to get inverted. Same with the YouTube icon, which would also get inverted when I wouldn't have changed the brightness threshold. I guess red icons in general are likely counted as dark, even when they would be easily see-able in the dark themes.

Also I guess I will make this an optional feature of some sort

**Comment by mmktomato** [comment]
I've pushed other commits to following branch.
https://github.com/mmktomato/vertical-tabs-reloaded/tree/invert-dark-favicons

#### 763b3a1c2574b1889134b8503c6bb081a13a1511
Skips inversion when some errors occur.

#### b03cd49da34fdefa73bbd3644fc9bc245011dcc9
Gives 'mode' param to FastAverageColor. 'precision' should give us precise result, I think. 

#### 4b8275818625c8638711602059ef8b98d80388b9
Uses rgb values to detect dark color instead of 'color.isDark'. I refer this StackOverflow.
https://stackoverflow.com/questions/13762864/image-dark-light-detection-client-sided-script
```javascript
function setText(text, averageColor, id){
  if(averageColor[0] <= 80 && averageColor[1] <= 80 && averageColor[2] <= 80){
     document.getElementById(id).innerHTML = "<font color='#ffffff'>"+text+"</font>";
  }
  else if(averageColor[0] >= 150 && averageColor[1] >= 150 && averageColor[2] >= 150){
     document.getElementById(id).innerHTML = "<font color='#000000'>"+text+"</font>";
  } 
}
```

#### e9c3b1a211bcb8961d03218462c0bd565148d660
Fixes list errors. ....I always fotget about lint 😓

inverted

What do you think these changes?

**Comment by mmktomato** [comment]
> https://github.com/mmktomato/vertical-tabs-reloaded/tree/invert-dark-favicons

It works good for me. I will recreate another pull request. So I will close this.

**Pull request closed without merging**
