### PR TITLE
Show a border line when dragging a tab 

### PR DESCRIPTION
**Pull request by mmktomato**
I've implemented showing a border line when an user is dragging a tab.
Please see attachment.
vtr

### CODE REVIEW

**Comment by Croydon** [comment]
Can we prevent that the favicons and (sometimes the tab titles? can't reproduce that anymore but had this once) are jumping up and down a little while dragging a tab over them?

**Comment by mmktomato** [comment]
I've almost fixed it. But we can't prevent it only about top tab. (Please see attached gif.)
Because, for now, border of hovered tab is changed while dragging a tab.
I think a (white) dom element need to be inserted dynamically between tabs to prevent it perfectly.

vtr2

**Comment by Croydon** [comment]
I think this is good enough for now. Good job!

This is now live in the [developer version](https://addons.mozilla.org/de/firefox/addon/vtr-developer-version/). I will merge it in master in a few days.

**Comment by Croydon** [comment]
Merged via https://github.com/Croydon/vertical-tabs-reloaded/commit/f05252bffe6f6dacbe46f002f862729d08ae6e52, https://github.com/Croydon/vertical-tabs-reloaded/commit/18cccd8e710a9bb7e5878c249577eda32cda1b63 and https://github.com/Croydon/vertical-tabs-reloaded/commit/dfd20c741ce4bd31f6d55a8651cbf3fe68158dd6

**Pull request closed without merging**
