### PR TITLE
fix: issue #150

### PR DESCRIPTION
**Pull request by mmktomato**
Hi.

I fixed issue #150 .
This is caused by `VerticalTabsReloaded.selectedTabID` is undefined.
And the delay time (10ms) of `setTimeout` within `init` is not enough for my environment. So I set it 100ms.
Please review PR.

Regards,

### CODE REVIEW

**Comment by Croydon** [comment]
@mmktomato Thank you very much for contributing!

However, I guess that I have fixed this as a byproduct of fixing #148. Could you please test version 0.9.2 and report if this fixes the problem also for you?

**Comment by mmktomato** [comment]
@Croydon Thank you for replying.

I tried version 0.9.2, but the problem is not fixed.
It seems that `tabElement.getBoundingClientRect()` (this is called within `scroll_to_tab` method) returns wrong value.
If I set a breakpoint to the line and step over (hit F10), the problem does not appeared. But Removing the breakpoint, it appears.

I fixed this in the following commit. But I don't know if this way is correct.

https://github.com/mmktomato/vertical-tabs-reloaded/commit/6e34cb67733286711790042beb32343196a19cdc

**Comment by Croydon** [comment]
@mmktomato Your second commits looks good to me. Could you increase the time out to 200ms? This should fix #151 then.

**Comment by mmktomato** [comment]
@Croydon I did it and pushed. Please review it.

**Comment by Croydon** [comment]
I have merged your commit here: https://github.com/Croydon/vertical-tabs-reloaded/commit/c81c80d540590b22ca64a96dd0157f51da997524

@mmktomato Could you please check out version 0.9.4 and see if it is working for you as expected?

**Comment by mmktomato** [comment]
@Croydon I tried 0.9.4 and it works fine. Thank you for merging!

**Comment by Croydon** [comment]
@mmktomato Thank you for contributing 😄

**Pull request closed without merging**
